version: '3.4'
services:

  app:
    build: .
    command: sleep infinity
    volumes:
      - .:/workspace:cached
    depends_on:
      - database
    networks:
      - bridge

  database:
    image: postgres:12.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - bridge

networks:
  bridge:
    driver: bridge